### ISSUE TITLE
[Request] 1.16.5 You Died

### ISSUE THREAD

**Issue by nwarshawsky** [GoryMoon/YouDied#1]
Hi, I was wondering if you could publish a 1.16.5 version of the You Died mod really quick! I want to include it in a modpack that I've spent the last few months making inspired by Dark Souls. I want to publish the pack tomorrow so anytime that day (03/02/2022) would be AMAZING. If you do this I will love you forever

**Comment by GoryMoon** [comment]
Just released the 1.16.5 version of the mod here: https://www.curseforge.com/minecraft/mc-mods/you-died/files/3670055
