### ISSUE TITLE
Clients crash when they die on a server that doesn't have the mod

### ISSUE THREAD

**Issue by Lantis-Hegg** [GoryMoon/YouDied#19]
This mod seems to be client sided, yet the client will crash when they die if they are connected to a server that doesn't have the mod. The full logs only point at the registry error shown in the image. The curseforge and general documentation doesn't specify weather or not this mod is client sided.

Here's the crash logs to look through:
[crash-2023-01-29_14.56.54-client.txt](https://github.com/GoryMoon/YouDied/files/10530704/crash-2023-01-29_14.56.54-client.txt)

![image](https://user-images.githubusercontent.com/123079950/215352448-b199b91c-0b40-4b5e-8d16-dc5fb598953e.png)

**Comment by GoryMoon** [comment]
Thanks for the report, a fix for this is now available to download.
I've also fixed this in the other versions as well.
