### ISSUE TITLE
Game crashes everytime you die

### ISSUE THREAD

**Issue by Deathstriker3004** [GoryMoon/YouDied#4]
I installed the mod, for a dark souls modpack, but everytime i die the game crashes.
I've tried: reinstalling the mod, getting its optional config, reinsalling the modpack.
Version: 1.16.5.

**Comment by GoryMoon** [comment]
Would need a crashlog to identify/fix the potential mod conflict.

**Comment by Deathstriker3004** [comment]
It just says that it may be a invalid configuration of java runtime
![image](https://user-images.githubusercontent.com/102868897/166113157-e2b8a659-a40f-4509-915e-f2a6f3d0c01d.png)
also sorry for it to be in portuguese because i am brazilian.
