### ISSUE TITLE
Death Loop

### ISSUE THREAD

**Issue by iWisd0M5d** [GoryMoon/YouDied#7]
When i die and respawn but its act like if i still  death and i cant move does epic fight and better third person affect that or no?

**Comment by GoryMoon** [comment]
I need version of game and other mods (and their version) used to be able to debug this.
This mod only affects the client aa it ontly replaces the deathscreen, so it shouldn't affect any respawn logic.

**Comment by iWisd0M5d** [comment]
1.18.2 the version game those 2 mods are 1.18.2 version to
