### ISSUE TITLE
Crashes when you die

### ISSUE THREAD

**Issue by Oxycity** [GoryMoon/YouDied#8]
[latest.log](https://github.com/GoryMoon/YouDied/files/8473568/latest.log)

Tried playing AsianHalfSquats elden ring remake in minecraft and this mod was an obvious coice but the only problem is that it crashes whenever i get killed would be nice if this would be patched. Thanks :D

**Comment by Oxycity** [comment]
I havent restarted it, i havent opened it since it crashed. Must i open it or re-crash it?

**Comment by GoryMoon** [comment]
Missed that was the log was when you died, can you upload the crash report?

**Comment by Oxycity** [comment]
sorry for the reaaally late reply but i couldnt rlly find any crash logs, all i can see is the lastest log
